/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import coins from "./coins.glb"
import {useFrame} from "@react-three/fiber";

export default function Coins({ coinsAnimate, showCoins, participation }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(coins)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions[coinsAnimate].reset().fadeIn(0.5).play()
    // return () => {actions["animeCoinsTwo"].fadeOut(0.5)}
  }, [actions]);

  return (
    <group ref={group} dispose={null} scale={10} visible={showCoins}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.8, -0.81, -0.03]}>
          <mesh geometry={nodes.Mesh_0.geometry} material={nodes.Mesh_0.material} />
          <mesh geometry={nodes.Mesh_1.geometry} material={nodes.Mesh_1.material} />
        </group>
      </group>
      <group

        name="RootNode_(gltf_orientation_matrix)001"
        position={[-0.09, -0.62, 0.12]}
        rotation={[1.53, 0.19, -0.06]}
        scale={[0.12, 0.11, 0.11]}>
        <group scale={0.14}>
          <group rotation={[Math.PI / 2, 0, 0]} >
            <group name="CoinObj" rotation={[0, -0.16, 0]}>
              <mesh
                name="CoinObj_Coin_0001"
                geometry={nodes.CoinObj_Coin_0001.geometry}
                material={nodes.CoinObj_Coin_0001.material}
                position={[-0.28, 0.54, -0.13]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.11}
              />
              <mesh
                name="CoinObj_Coin_0002"
                geometry={nodes.CoinObj_Coin_0002.geometry}
                material={nodes.CoinObj_Coin_0002.material}
                position={[6.88, -35.68, 21.16]}
                rotation={[-1.47, -0.14, 0.16]}
                scale={[0.67, 0.67, 0.67]}
              />
              <mesh
                name="CoinObj_Coin_0003"
                geometry={nodes.CoinObj_Coin_0003.geometry}
                material={nodes.CoinObj_Coin_0003.material}
                position={[-0.28, 0.54, -0.13]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.11}
              />
              <mesh
                name="CoinObj_Coin_0004"
                geometry={nodes.CoinObj_Coin_0004.geometry}
                material={nodes.CoinObj_Coin_0004.material}
                position={[36.02, -35.07, 2.98]}
                rotation={[-1.47, -0.14, 0.16]}
                scale={[0.67, 0.67, 0.67]}
              />
              <mesh
                name="CoinObj_Coin_0005"
                geometry={nodes.CoinObj_Coin_0005.geometry}
                material={nodes.CoinObj_Coin_0005.material}
                position={[15.5, -34.83, -18.52]}
                rotation={[-1.47, -0.14, 0.16]}
                scale={[0.67, 0.67, 0.67]}
              />
              <mesh
                name="CoinObj_Coin_0"
                geometry={nodes.CoinObj_Coin_0.geometry}
                material={nodes.CoinObj_Coin_0.material}
                position={[4.76, -34.83, -1.05]}
                rotation={[-1.47, -0.14, 0.16]}
                scale={[0.67, 0.67, 0.67]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/coins.glb')
