/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef, useState} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import handModel from './hand-model01.glb'
import {useResponsive3d} from "../../customHooks/useResponsive3d";

export default function HandModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(handModel)
  const { actions } = useAnimations(animations, group)

    //sets finger movement
    const [action] = useState("fingerMove")

    useEffect(() => {
        actions[action].reset().fadeIn(0.5).play()
        // setMouseButtonColor("#a0e734")
        return () => actions[action].fadeOut(0.5)
    }, [actions, action]);

    const {fingerVisible} = useResponsive3d()

  return (
    <group ref={group} {...props} dispose={null} visible={fingerVisible}>
      <mesh
        name="node_MeshObject-1005584384-PolyPaper23"
        geometry={nodes['node_MeshObject-1005584384-PolyPaper23'].geometry}
        material={materials.BlocksPaper}
        // position={[-1.7, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(handModel)
