/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import blenderGLB from './blender.glb'

export default function Blender(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(blenderGLB)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['SVGMat.033']} />
        <mesh geometry={nodes.Object_2.geometry} material={materials['SVGMat.024']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['SVGMat.026']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['SVGMat.027']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['SVGMat.028']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['SVGMat.029']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['SVGMat.030']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['SVGMat.031']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['SVGMat.032']} />
      </group>
    </group>
  )
}

useGLTF.preload(blenderGLB)
