/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Planet01() {
  const planet = useRef()
  const clouds = useRef()
  const { nodes, materials } = useGLTF('/planets/planet-01-transformed.glb')

  //animate the planet and clouds at different speeds
  useFrame(({ clock }) => {
    planet.current.rotation.z = clock.getElapsedTime() / 2
    clouds.current.rotation.z = clock.getElapsedTime() / 4
  })

  return (
    <group rotation={[-Math.PI / 2, .30, 0]} scale={1.02}>
      <group ref={clouds}>
        <mesh geometry={nodes.Clouds_1_0.geometry} material={materials.Clouds_1} />
      </group>
      <group ref={planet}>
        <mesh geometry={nodes.Clouds_0_0.geometry} material={materials.Clouds_0} />
        <mesh geometry={nodes.Planet_0.geometry} material={materials.PurplePlanet} />
      </group>
    </group>
  )
}

useGLTF.preload('/planets/planet-01-transformed.glb')
