/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Arrow({ xPosition, yPosition, zPosition, arrowRotation }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/arrow_01-transformed.glb')

  // aboutMe = [1.57, 2.094, 0] skillz = [-0.785, 0, 1.57] experience = [-1.57, -2.094, Math.PI] Websites = [0.785, Math.PI, 1.57] 
  return (
    <group ref={group} dispose={null}>
      <group position={[xPosition, yPosition, zPosition]} rotation={arrowRotation} scale={0.002}>
        <mesh geometry={nodes.Cube__0.geometry} material={materials.Cube_2__0} />
        <mesh geometry={nodes.Cube_Mat1_0.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Cube_Mat_0.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/arrow_01-transformed.glb')
