/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: xenadus (https://sketchfab.com/xenadus)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
title: React logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function ReactLogo({ ...props }) {
  const logo = useRef()
  const { nodes, materials } = useGLTF('/react_logo.glb')

  useFrame(({ clock }) => {
    const ticks = clock.getElapsedTime()

    logo.current.rotation.y = ticks
  })
  return (
    <group
      ref={logo}
      position={[20, 0, 6]}
      rotation={[0, -1.570796, 1.5]}
      scale={1}>
      <mesh geometry={nodes['React-Logo_Material002_0'].geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/react_logo.glb')
