/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import christmasHat from './christmas-hat-01.glb'
import {useFrame} from "@react-three/fiber";

export default function ChristmasHat01({ showCoins }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(christmasHat)

    const hat = useRef()

    useFrame(({clock}) => {
        hat.current.rotation.y = Math.sin(clock.getElapsedTime())/10
    })

  return (
    <group ref={group} dispose={null} scale={0.5} visible={showCoins}>
      <group rotation={[-Math.PI / 1.6, 0.3, 0]}>
        <group rotation={[0.37, -0.04, -0.11]} ref={hat}>
          <mesh geometry={nodes.Mesh_0.geometry} material={materials.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/christmas-hat-01.glb')
