/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef, useState} from 'react'
import {useGLTF} from '@react-three/drei'
import christmasPresent from "./christmas-present.glb"
import {useSpring, animated} from "@react-spring/three";
import {useFrame} from "@react-three/fiber";
import {Button} from "react-bootstrap";
import {httpConfig} from "../../ui/shared/utils/http-config";
import {fetchParticipation} from "../../store/eventParticipationSlices/participationSlice";
import {fetchProfileByProfileId} from "../../store/profileSlice";
import {useDispatch} from "react-redux";

export default function ChristmasPresent({participation, profile, presentOpened}) {
    const group = useRef()
    const {nodes, materials} = useGLTF(christmasPresent)

    //present clicked
    const [active, setActive] = useState(false)

    //changes size of present onCLick
    const {changeScale} = useSpring({
        changeScale: active ? 1.5 : 1,
        // to: {changeScale: 10},
        // from: {changeScale: 0,}
    })


    const present = useRef()

    //present rotation animation
    useFrame(({clock}) => {
        present.current.rotation.y = Math.sin(clock.getElapsedTime())
    })




    return (
        <group ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0.1, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, 4.09, 0]} scale={20} >
                        <animated.mesh ref={present}
                                       geometry={nodes.christmas_present_Present_0.geometry}
                                       material={materials.Present}
                                       scale={changeScale}
                                       onClick={() => {
                                           setActive(true)
                                       }}/>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/christmas-present.glb')
