/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 code-logo.glb --transform --keepmeshes 
Files: code-logo.glb [5.34KB] > code-logo-transformed.glb [3.13KB] (41%)
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function CodeLogo(props) {
  const { nodes } = useGLTF('/logos/code-logo-transformed.glb')

  let loadedTexture = useTexture("/textures/blue_02_matCap.png")

  return (
    <group rotation={[1.5708, 0, 3.14159]}>
      <mesh geometry={nodes.circle.geometry} material={nodes.circle.material} position={[0.002, -0.011, 0]} scale={100}>
        <meshMatcapMaterial matcap={loadedTexture} />
      </mesh>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-0.652, 0.078, 0.227]} scale={0.65}>
        <meshMatcapMaterial matcap={loadedTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/logos/code-logo-transformed.glb')
